// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/vitals/v1/vitals.proto

package vitalsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertStatus int32

const (
	AlertStatus_ALERT_STATUS_ACTIVE        AlertStatus = 0
	AlertStatus_ALERT_STATUS_RESOLVED      AlertStatus = 1
	AlertStatus_ALERT_STATUS_AUTO_RESOLVED AlertStatus = 2
)

// Enum value maps for AlertStatus.
var (
	AlertStatus_name = map[int32]string{
		0: "ALERT_STATUS_ACTIVE",
		1: "ALERT_STATUS_RESOLVED",
		2: "ALERT_STATUS_AUTO_RESOLVED",
	}
	AlertStatus_value = map[string]int32{
		"ALERT_STATUS_ACTIVE":        0,
		"ALERT_STATUS_RESOLVED":      1,
		"ALERT_STATUS_AUTO_RESOLVED": 2,
	}
)

func (x AlertStatus) Enum() *AlertStatus {
	p := new(AlertStatus)
	*p = x
	return p
}

func (x AlertStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_vitals_v1_vitals_proto_enumTypes[0].Descriptor()
}

func (AlertStatus) Type() protoreflect.EnumType {
	return &file_proto_vitals_v1_vitals_proto_enumTypes[0]
}

func (x AlertStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertStatus.Descriptor instead.
func (AlertStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_vitals_v1_vitals_proto_rawDescGZIP(), []int{0}
}

type IngestVitalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Systolic      int32                  `protobuf:"varint,2,opt,name=systolic,proto3" json:"systolic,omitempty"`
	Diastolic     int32                  `protobuf:"varint,3,opt,name=diastolic,proto3" json:"diastolic,omitempty"`
	TakenAt       int64                  `protobuf:"varint,4,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestVitalRequest) Reset() {
	*x = IngestVitalRequest{}
	mi := &file_proto_vitals_v1_vitals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestVitalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestVitalRequest) ProtoMessage() {}

func (x *IngestVitalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vitals_v1_vitals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestVitalRequest.ProtoReflect.Descriptor instead.
func (*IngestVitalRequest) Descriptor() ([]byte, []int) {
	return file_proto_vitals_v1_vitals_proto_rawDescGZIP(), []int{0}
}

func (x *IngestVitalRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *IngestVitalRequest) GetSystolic() int32 {
	if x != nil {
		return x.Systolic
	}
	return 0
}

func (x *IngestVitalRequest) GetDiastolic() int32 {
	if x != nil {
		return x.Diastolic
	}
	return 0
}

func (x *IngestVitalRequest) GetTakenAt() int64 {
	if x != nil {
		return x.TakenAt
	}
	return 0
}

type IngestVitalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vital         *Vital                 `protobuf:"bytes,1,opt,name=vital,proto3" json:"vital,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestVitalResponse) Reset() {
	*x = IngestVitalResponse{}
	mi := &file_proto_vitals_v1_vitals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestVitalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestVitalResponse) ProtoMessage() {}

func (x *IngestVitalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vitals_v1_vitals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestVitalResponse.ProtoReflect.Descriptor instead.
func (*IngestVitalResponse) Descriptor() ([]byte, []int) {
	return file_proto_vitals_v1_vitals_proto_rawDescGZIP(), []int{1}
}

func (x *IngestVitalResponse) GetVital() *Vital {
	if x != nil {
		return x.Vital
	}
	return nil
}

type ListAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsRequest) Reset() {
	*x = ListAlertsRequest{}
	mi := &file_proto_vitals_v1_vitals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsRequest) ProtoMessage() {}

func (x *ListAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vitals_v1_vitals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListAlertsRequest) Descriptor() ([]byte, []int) {
	return file_proto_vitals_v1_vitals_proto_rawDescGZIP(), []int{2}
}

func (x *ListAlertsRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type ListAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsResponse) Reset() {
	*x = ListAlertsResponse{}
	mi := &file_proto_vitals_v1_vitals_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsResponse) ProtoMessage() {}

func (x *ListAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vitals_v1_vitals_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertsResponse) Descriptor() ([]byte, []int) {
	return file_proto_vitals_v1_vitals_proto_rawDescGZIP(), []int{3}
}

func (x *ListAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type Vital struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Systolic      int32                  `protobuf:"varint,3,opt,name=systolic,proto3" json:"systolic,omitempty"`
	Diastolic     int32                  `protobuf:"varint,4,opt,name=diastolic,proto3" json:"diastolic,omitempty"`
	TakenAt       int64                  `protobuf:"varint,5,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	ReceivedAt    int64                  `protobuf:"varint,6,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vital) Reset() {
	*x = Vital{}
	mi := &file_proto_vitals_v1_vitals_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vital) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vital) ProtoMessage() {}

func (x *Vital) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vitals_v1_vitals_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vital.ProtoReflect.Descriptor instead.
func (*Vital) Descriptor() ([]byte, []int) {
	return file_proto_vitals_v1_vitals_proto_rawDescGZIP(), []int{4}
}

func (x *Vital) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vital) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *Vital) GetSystolic() int32 {
	if x != nil {
		return x.Systolic
	}
	return 0
}

func (x *Vital) GetDiastolic() int32 {
	if x != nil {
		return x.Diastolic
	}
	return 0
}

func (x *Vital) GetTakenAt() int64 {
	if x != nil {
		return x.TakenAt
	}
	return 0
}

func (x *Vital) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vital         *Vital                 `protobuf:"bytes,2,opt,name=vital,proto3" json:"vital,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status        AlertStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=vitals.v1.AlertStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_vitals_v1_vitals_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vitals_v1_vitals_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_vitals_v1_vitals_proto_rawDescGZIP(), []int{5}
}

func (x *Alert) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Alert) GetVital() *Vital {
	if x != nil {
		return x.Vital
	}
	return nil
}

func (x *Alert) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Alert) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Alert) GetStatus() AlertStatus {
	if x != nil {
		return x.Status
	}
	return AlertStatus_ALERT_STATUS_ACTIVE
}

var File_proto_vitals_v1_vitals_proto protoreflect.FileDescriptor

const file_proto_vitals_v1_vitals_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/vitals/v1/vitals.proto\x12\tvitals.v1\"\x88\x01\n" +
	"\x12IngestVitalRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x1a\n" +
	"\bsystolic\x18\x02 \x01(\x05R\bsystolic\x12\x1c\n" +
	"\tdiastolic\x18\x03 \x01(\x05R\tdiastolic\x12\x19\n" +
	"\btaken_at\x18\x04 \x01(\x03R\atakenAt\"=\n" +
	"\x13IngestVitalResponse\x12&\n" +
	"\x05vital\x18\x01 \x01(\v2\x10.vitals.v1.VitalR\x05vital\"2\n" +
	"\x11ListAlertsRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\">\n" +
	"\x12ListAlertsResponse\x12(\n" +
	"\x06alerts\x18\x01 \x03(\v2\x10.vitals.v1.AlertR\x06alerts\"\xac\x01\n" +
	"\x05Vital\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1a\n" +
	"\bsystolic\x18\x03 \x01(\x05R\bsystolic\x12\x1c\n" +
	"\tdiastolic\x18\x04 \x01(\x05R\tdiastolic\x12\x19\n" +
	"\btaken_at\x18\x05 \x01(\x03R\atakenAt\x12\x1f\n" +
	"\vreceived_at\x18\x06 \x01(\x03R\n" +
	"receivedAt\"\xa6\x01\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x05vital\x18\x02 \x01(\v2\x10.vitals.v1.VitalR\x05vital\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.vitals.v1.AlertStatusR\x06status*a\n" +
	"\vAlertStatus\x12\x17\n" +
	"\x13ALERT_STATUS_ACTIVE\x10\x00\x12\x19\n" +
	"\x15ALERT_STATUS_RESOLVED\x10\x01\x12\x1e\n" +
	"\x1aALERT_STATUS_AUTO_RESOLVED\x10\x022\xa8\x01\n" +
	"\rVitalsService\x12L\n" +
	"\vIngestVital\x12\x1d.vitals.v1.IngestVitalRequest\x1a\x1e.vitals.v1.IngestVitalResponse\x12I\n" +
	"\n" +
	"ListAlerts\x12\x1c.vitals.v1.ListAlertsRequest\x1a\x1d.vitals.v1.ListAlertsResponseB3Z1cadence-vitals-interview/proto/vitals/v1;vitalsv1b\x06proto3"

var (
	file_proto_vitals_v1_vitals_proto_rawDescOnce sync.Once
	file_proto_vitals_v1_vitals_proto_rawDescData []byte
)

func file_proto_vitals_v1_vitals_proto_rawDescGZIP() []byte {
	file_proto_vitals_v1_vitals_proto_rawDescOnce.Do(func() {
		file_proto_vitals_v1_vitals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vitals_v1_vitals_proto_rawDesc), len(file_proto_vitals_v1_vitals_proto_rawDesc)))
	})
	return file_proto_vitals_v1_vitals_proto_rawDescData
}

var file_proto_vitals_v1_vitals_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_vitals_v1_vitals_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_vitals_v1_vitals_proto_goTypes = []any{
	(AlertStatus)(0),            // 0: vitals.v1.AlertStatus
	(*IngestVitalRequest)(nil),  // 1: vitals.v1.IngestVitalRequest
	(*IngestVitalResponse)(nil), // 2: vitals.v1.IngestVitalResponse
	(*ListAlertsRequest)(nil),   // 3: vitals.v1.ListAlertsRequest
	(*ListAlertsResponse)(nil),  // 4: vitals.v1.ListAlertsResponse
	(*Vital)(nil),               // 5: vitals.v1.Vital
	(*Alert)(nil),               // 6: vitals.v1.Alert
}
var file_proto_vitals_v1_vitals_proto_depIdxs = []int32{
	5, // 0: vitals.v1.IngestVitalResponse.vital:type_name -> vitals.v1.Vital
	6, // 1: vitals.v1.ListAlertsResponse.alerts:type_name -> vitals.v1.Alert
	5, // 2: vitals.v1.Alert.vital:type_name -> vitals.v1.Vital
	0, // 3: vitals.v1.Alert.status:type_name -> vitals.v1.AlertStatus
	1, // 4: vitals.v1.VitalsService.IngestVital:input_type -> vitals.v1.IngestVitalRequest
	3, // 5: vitals.v1.VitalsService.ListAlerts:input_type -> vitals.v1.ListAlertsRequest
	2, // 6: vitals.v1.VitalsService.IngestVital:output_type -> vitals.v1.IngestVitalResponse
	4, // 7: vitals.v1.VitalsService.ListAlerts:output_type -> vitals.v1.ListAlertsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_vitals_v1_vitals_proto_init() }
func file_proto_vitals_v1_vitals_proto_init() {
	if File_proto_vitals_v1_vitals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vitals_v1_vitals_proto_rawDesc), len(file_proto_vitals_v1_vitals_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vitals_v1_vitals_proto_goTypes,
		DependencyIndexes: file_proto_vitals_v1_vitals_proto_depIdxs,
		EnumInfos:         file_proto_vitals_v1_vitals_proto_enumTypes,
		MessageInfos:      file_proto_vitals_v1_vitals_proto_msgTypes,
	}.Build()
	File_proto_vitals_v1_vitals_proto = out.File
	file_proto_vitals_v1_vitals_proto_goTypes = nil
	file_proto_vitals_v1_vitals_proto_depIdxs = nil
}
