// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/vitals/v1/vitals.proto

package vitalsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VitalsService_IngestVital_FullMethodName = "/vitals.v1.VitalsService/IngestVital"
	VitalsService_ListAlerts_FullMethodName  = "/vitals.v1.VitalsService/ListAlerts"
)

// VitalsServiceClient is the client API for VitalsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VitalsServiceClient interface {
	IngestVital(ctx context.Context, in *IngestVitalRequest, opts ...grpc.CallOption) (*IngestVitalResponse, error)
	ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error)
}

type vitalsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVitalsServiceClient(cc grpc.ClientConnInterface) VitalsServiceClient {
	return &vitalsServiceClient{cc}
}

func (c *vitalsServiceClient) IngestVital(ctx context.Context, in *IngestVitalRequest, opts ...grpc.CallOption) (*IngestVitalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestVitalResponse)
	err := c.cc.Invoke(ctx, VitalsService_IngestVital_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vitalsServiceClient) ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertsResponse)
	err := c.cc.Invoke(ctx, VitalsService_ListAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VitalsServiceServer is the server API for VitalsService service.
// All implementations must embed UnimplementedVitalsServiceServer
// for forward compatibility.
type VitalsServiceServer interface {
	IngestVital(context.Context, *IngestVitalRequest) (*IngestVitalResponse, error)
	ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error)
	mustEmbedUnimplementedVitalsServiceServer()
}

// UnimplementedVitalsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVitalsServiceServer struct{}

func (UnimplementedVitalsServiceServer) IngestVital(context.Context, *IngestVitalRequest) (*IngestVitalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestVital not implemented")
}
func (UnimplementedVitalsServiceServer) ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAlerts not implemented")
}
func (UnimplementedVitalsServiceServer) mustEmbedUnimplementedVitalsServiceServer() {}
func (UnimplementedVitalsServiceServer) testEmbeddedByValue()                       {}

// UnsafeVitalsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VitalsServiceServer will
// result in compilation errors.
type UnsafeVitalsServiceServer interface {
	mustEmbedUnimplementedVitalsServiceServer()
}

func RegisterVitalsServiceServer(s grpc.ServiceRegistrar, srv VitalsServiceServer) {
	// If the following call panics, it indicates UnimplementedVitalsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VitalsService_ServiceDesc, srv)
}

func _VitalsService_IngestVital_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestVitalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VitalsServiceServer).IngestVital(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VitalsService_IngestVital_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VitalsServiceServer).IngestVital(ctx, req.(*IngestVitalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VitalsService_ListAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VitalsServiceServer).ListAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VitalsService_ListAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VitalsServiceServer).ListAlerts(ctx, req.(*ListAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VitalsService_ServiceDesc is the grpc.ServiceDesc for VitalsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VitalsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vitals.v1.VitalsService",
	HandlerType: (*VitalsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestVital",
			Handler:    _VitalsService_IngestVital_Handler,
		},
		{
			MethodName: "ListAlerts",
			Handler:    _VitalsService_ListAlerts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vitals/v1/vitals.proto",
}
